# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI/CD Pipeline

on:
  push:
    branches:
      - 'main'
      - 'feature-*'
      - 'release-*'
      - 'hotfix-*'
  pull_request:
    branches:
      - 'main'
      - 'release-*'
      - 'hotfix-*'

env:
  GCP_REGION: asia-northeast1
  GCP_PROJECT_ID: demoforgaudiy
  ARTIFACT_REGISTRY: maven
  DOCKER_REGISTRY: docker-local

jobs:
  build:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/feature-') || startsWith(github.ref, 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=GCPCICDDemo_spring-petclinic-microservices \
        -Dsonar.organization=gcpcicddemo \
        -Dsonar.host.url=https://sonarcloud.io 
      continue-on-error: true

    - name: Build Docker Images
      run: |
        ./mvnw clean install -P buildDocker

    - name: Check build status
      if: failure()
      run: exit 1

  build-and-deploy:
    runs-on: ubuntu-latest
    if: |
      startsWith(github.ref, 'refs/heads/release-') || 
      startsWith(github.ref, 'refs/heads/hotfix-') ||
      (github.event_name == 'pull_request' && (startsWith(github.base_ref, 'release-') || startsWith(github.base_ref, 'hotfix-')))
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and analyze
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
        -Dsonar.projectKey=GCPCICDDemo_spring-petclinic-microservices\
        -Dsonar.organization=gcpcicddemo \
        -Dsonar.host.url=https://sonarcloud.io 
      continue-on-error: true
        

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ secrets.GCP_SA_KEY }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Configure Docker for Artifact Registry
      run: |-
        gcloud auth configure-docker $GCP_REGION-docker.pkg.dev

    - name: Build Docker Images
      run: |-
        ./mvnw clean install -P buildDocker

     - name: Extract version from branch name
      run: |
        if [[ $GITHUB_EVENT_NAME == 'pull_request' ]]; then
          BRANCH_NAME=$GITHUB_BASE_REF
        else
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
        fi
        VERSION=${BRANCH_NAME#*-}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        
    - name: Push Docker images
      run: |-
        docker login asia-northeast1-docker.pkg.dev
        docker tag springcommunity/spring-petclinic-api-gateway $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-api-gateway:${{ env.VERSION }}
        docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-api-gateway:${{ env.VERSION }} 
        docker tag springcommunity/spring-petclinic-config-server $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-config-server:${{ env.VERSION }}
        docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-config-server:${{ env.VERSION }}
        docker tag springcommunity/spring-petclinic-discovery-server $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-discovery-server:${{ env.VERSION }}
        docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-discovery-server:${{ env.VERSION }}
        docker tag springcommunity/spring-petclinic-customers-service $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-customers-service:${{ env.VERSION }}
        docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-customers-service:${{ env.VERSION }}
        docker tag springcommunity/spring-petclinic-visits-service $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-visits-service:${{ env.VERSION }}
        docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-visits-service:${{ env.VERSION }}
        docker tag springcommunity/spring-petclinic-vets-service $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-vets-service:${{ env.VERSION }}
        docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-vets-service:${{ env.VERSION }}
        docker tag springcommunity/spring-petclinic-admin-server $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-admin-server:${{ env.VERSION }}
        docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$DOCKER_REGISTRY/spring-petclinic-microservices-admin-server:${{ env.VERSION }}

   
